### PR TITLE
Added format in message queries

### PR DESCRIPTION
**Pull request by satadipa**
In message queries, I have added support for format to return the message in. I have also updated the README on how to use it. Please let me know about your opinion.

### CODE REVIEW

**Comment by nathanbowser** [comment]
The logic for creating the query string is getting a little messy. What do you think about breaking that into a separate function and adding tests?

**Comment by satadipa** [comment]
Yeah, rightly agreed. I'll do the same and let you know.

**Comment by satadipa** [comment]
I have updated the logic for forming the query string. And, also have attempted to provide test. 
Any advice is welcome.

**Comment by nathanbowser** [comment]
Thanks. Node has a built in querystring builder I think you should use instead. 

https://nodejs.org/api/querystring.html#querystring_querystring_stringify_obj_sep_eq_options

**Comment by satadipa** [comment]
Thanks.

**Comment by nathanbowser** [comment]
No problem, @satadipa if you need a hand, just let me know. I can show you what I have in mind.

**Comment by satadipa** [comment]
Have you looked at the last commit **bfb25aba79af6226fc7e970f547e7096a08e4333**  ?

**Comment by nathanbowser** [comment]
Merged manually. + node-gmail-api@0.6.0

**Pull request closed without merging**
